# Penulisan nama service menggunakan huruf kecil
# Penulisan protocol menggunakan huruf kapital

kind: Service
apiVersion: v1
metadata:
  name: TENTUKAN_NAMA_SERVICE
  namespace: TENTUKAN_NAMESPACE
spec:
  selector:
    app: TENTUKAN_POD_BERDASARKAN_LABEL
  ports:
    - name: TENTUKAN_NAMA_PORT
      protocol: TENTUKAN_PROTOCOL
      port: TENTUKAN_PORT
      targetPort: TENTUKAN_PORT
